### ISSUE TITLE
Enabling viewer on dynamically loaded images

### ISSUE THREAD

**Issue by macsupport** [fengyuanchen/viewer#1]
I am loading a thumbnail dynamically using this code, which works fine.

```` 
$gallery.on( 'cellSelect' , function() {
  var element = flkty.selectedElement;
  var thumb = $(element).attr('data-thumb');
  var $thumbs = $(".thumbs");
  $thumbs.html( thumb );
  }); 
````
The data-thumb is formatted like this:

````
data-thumb='<img class="mini" data-original="slides/big.jpg" src="thumbs/small.jpg">
````
Viewer does not work with this dynamic image without using the following code but all the tools are wonky (rotation rotates it 360 degrees and many won't work.) and I can only get it to close by using destroy or hide.

````
$('.mini').viewer({
  });
  $('.thumbs').on('click',function(){
  $('.mini').viewer('show');
  });
  $('.viewer-close').on('click',function(){
  $('.mini').viewer('destroy');
  
  });
````

Any options for a dynamic image to work with viewer?

**Comment by fengyuanchen** [comment]
Restart the viewer once you load an image.
