### ISSUE TITLE
生成的代码加入到body下面会更好

### ISSUE THREAD

**Issue by lovewuyong** [fengyuanchen/viewer#12]
生成的代码不在body下的话，有时候会被overflow:hidden所影响

**Comment by fengyuanchen** [comment]
有道理，如果是`inline: false`，可以考虑放到`body`后。

**Comment by beijiyibei** [comment]
的确，$('.images').viewer();如果$('.images')元素是有滚动条的话，当你查看图片放大缩小时，$('.images')里的内容会也会上下滚动

**Comment by fengyuanchen** [comment]
已实现。
