### ISSUE TITLE
Parent with position: fixed

### ISSUE THREAD

**Issue by vatavale** [fengyuanchen/viewer#13]
When I use Viewer for images inside fixed-position block, it opens inside this block, not fillings all browser window. Fullscreen mode also do not work at this situation.

**Comment by vatavale** [comment]
Looks like it's connected with placement of Viewer container. And then parent have overflow:hidden.
Is it possible to have option to create Viewer container inside <body> tag?

**Comment by fengyuanchen** [comment]
I will improve this later, thanks~

**Comment by fengyuanchen** [comment]
In modal mode, the viewer will be appended to body now.
