### ISSUE TITLE
图片的拖动，缩放的交互逻辑问题

### ISSUE THREAD

**Issue by yulanggong** [fengyuanchen/viewer#16]
总觉得现在的拖动和缩放怪怪的，研究了一些其他图片查看软件的交互方式，发现一些共有的交互逻辑：

图片宽或高小于画布对应的宽或高时，这个轴向的拖动会被禁用，这个轴向的缩放原点不会用事件触发的坐标而是用画布中心点。
图片宽或高大于画布对应的宽或高时，这个轴向的拖动会受限到一定范围内，以保证图片区域完全包含画布区域（类似滚动条出现时的拖动交互方式），缩放的原点使用事件触发的坐标。

我 fork 了一个版本实现了这样的交互，因为不知道你对这种交互逻辑是否认可，所以还没有提交 pr。

**Comment by fengyuanchen** [comment]
限制诚可恶，自由价更高。
