### ISSUE TITLE
多图片查看，首张图片显示不对

### ISSUE THREAD

**Issue by filljoys** [fengyuanchen/viewer#2]
### 重现步骤：
> 官方 [Demo](http://fengyuanchen.github.io/viewer/) 为例

- 随便点击一张图片（放大），不是第一张即可
- 再次点击第一张图片（放大），此时放大后的图片为上次点击图片

初步认为原因：
```javascript
this.view((this.target ? this.$images.index(this.target) : 0) || this.index);
```
插件很给力，谢谢作者的贡献！希望尽快修复

**Comment by fengyuanchen** [comment]
Thank you  for the feedback. I will fix this issue soon. :christmas_tree: :santa: :snowman:
