### ISSUE TITLE
I take some data-* attr in img,how can I get it in "viewed" event or else event?

### ISSUE THREAD

**Issue by paul2008** [fengyuanchen/viewer#20]
` <img data-original="/Images/pdf.jpg"  src="/Images/pdf.jpg" data-docid="youdoc">`
` <img data-original="/Images/pdf.jpg"  src="/Images/pdf.jpg" data-docid="mydoc">`

I want to get data-docid value in event handler

**Comment by fengyuanchen** [comment]
Not support this.
