### ISSUE TITLE
Mouse wheel zoom in outside pic

### ISSUE THREAD

**Issue by paul2008** [fengyuanchen/viewer#21]
When I wheel my mouse  in Red area,the picture still zoom. But For Move action, I must mouse "on" Picture.
Can i zoom pic  like move action ,only reaction when mouse on pic. 

![qq 20160527154236](https://cloud.githubusercontent.com/assets/10897724/15601449/f3d2f304-2421-11e6-98ed-495678a68e83.png)

**Comment by fengyuanchen** [comment]
When the image is very small, it is hard to move to operate on it.

**Comment by paul2008** [comment]
When mouse hover in control , it not page down ,just zoom in/out pic.
I think only when mouse hover in pic (not control) to zoom  ,may be better.
