### ISSUE TITLE
Open the viewer automatically

### ISSUE THREAD

**Issue by marcelotq** [fengyuanchen/viewer#22]
Hello good day.

Is there any way to automatically open the viewer , displaying the first image in the gallery?

Thanks for the support and congratulations for the work .

Regards,
Marcelo

**Comment by fengyuanchen** [comment]
Why not read the documentation first? Didn't you see the `show` method?

**Comment by marcelotq** [comment]
Hi, thanks by the answer. I read the documentation and I try use the show method, but doesn`t works.

I will try with another way.

Thanks by help and congratulations for the work!


Regards,
Marcelo
