### ISSUE TITLE
Disable reset size when resizing the parent element

### ISSUE THREAD

**Issue by hectorgr** [fengyuanchen/viewer#25]
I created various popups with your plugin using the 'inline' option, and also I use jqueryUI for add draggable and resizable interactions. The problem is when I resize the containter or the webBrowser window, all images in viewers change to initial size.
For example, in your demo, when you do zoom in the image and then the webrowser is resized, the zoom is lost.
how can I do for disable this reset size?

**Comment by fengyuanchen** [comment]
Just set a fixed width to the viewer container.
