### ISSUE TITLE
你好，如果图片时变化的，是由ajax获取数据，再拼接生成的，是否支持？

### ISSUE THREAD

**Issue by kzjxm** [fengyuanchen/viewer#26]
你好，如果图片时变化的，是由ajax获取数据，再拼接生成的，是否支持？

**Comment by fengyuanchen** [comment]
https://github.com/fengyuanchen/viewer#update

**Comment by beijiyibei** [comment]
我是这样调用的：$('#chat-room').viewer('update').viewer({
                    url: 'data-original',
                    navbar: false,  //关闭缩略图导航
                    title: false,   //关闭当前图片的标题（现实 alt 属性及图片尺寸）
                    scalable: false, //图片是否可翻转
                    fullscreen: false,  //是否全屏播放
                    play: false,     //关闭自动播放
                    reset: false    //关闭重置功能
                });
，但是有个问题，update会显示所有的按钮，而不是根据我配置来显示

**Comment by naffan2014** [comment]
你调用反了。应该这样：
`
$('#chat-room').viewer({
url: 'data-original',
navbar: false, //关闭缩略图导航
title: false, //关闭当前图片的标题（现实 alt 属性及图片尺寸）
scalable: false, //图片是否可翻转
fullscreen: false, //是否全屏播放
play: false, //关闭自动播放
reset: false //关闭重置功能
}).viewer('update');

`
