### ISSUE TITLE
是否可以通过点击灰色区域退出浏览？

### ISSUE THREAD

**Issue by lonlie** [fengyuanchen/viewer#27]
目前可以通过右上角的“X”按钮和“Esc”退出浏览模式，想问下是否可以通过点击灰色区域退出浏览？
谢谢！

**Comment by fengyuanchen** [comment]
可以通过事件代理，在`<body>`上绑定点击事件，当用户点击透明区域（对应的元素）时，调用`hide`方法关闭浏览窗口。

**Comment by lonlie** [comment]
好的，多谢提示！
