### ISSUE TITLE
Improve performance for lots of thumbnails?

### ISSUE THREAD

**Issue by nabeygun** [fengyuanchen/viewer#28]
Hi,

Would it be possible to introduce some methods in order to improve the performance of the image viewer - for example, I am trying to load the image viewer with about 800 images. Would it be possible to defer or lazy load the thumbnails which are not yet visible when first invoked? There is another javascript image viewer which offers this functionality:
http://galleria.io/docs/references/optimize/#lazy-load-thumbnails
See points 3 and 6 in the above link.

Please let me know what you think. Thanks for your image viewer!

**Comment by fengyuanchen** [comment]
Just download the images page by page, and each time one page images loaded, call the `update` method to add them to the viewer.

**Comment by nabeygun** [comment]
Thanks for your reply..

**Comment by nabeygun** [comment]
We managed to find a way to lazy load the thumbnails using the following lightweight jquery plugin: http://luis-almeida.github.io/unveil/

Initially, the 800 thumbnails on the page are hidden and they each have a common placeholder image. We are then calling unveil function on a subset of the images (about 21 images) which goes to replace the placeholder image with the actual image. As the user navigates the thumbnails, the thumbnails are being replaced with their actual images URLs too.

**Comment by yavuz** [comment]
@nabeygun How did you do that? Can you share example code? Unfortunately I could not.

@fengyuanchen  Also when I `update`, the viewer always turn first image. Is this normal?

**Comment by nabeygun** [comment]
@yavuz Unfortunately, I cannot show my example code but I can try to explain through the changes. We used the unveil jquery plugin in the following manner:
In viewer.js, we edited the constructor _function Viewer(element, options) {_ to add the below line:
`    this.unveilImages = false;`

Then, we edited the _renderList_ function to insert the below code:

```
      // Unveil jQuery plugin is being used for lazy loading of thumbnail images.
      // A maximum of 20 thumbnails will be loaded upon opening of the Image Viewer.
      // As user navigates using Next/Previous buttons, further thumbnails will be loaded asynchronously.
      if (this.unveilImages) {
    	  if (this.length >= 20) {
    		  var elements;
    		  if (i <= 9) {
    			  elements = $("img.lazyImage").slice(0, 20);
    		  } else {
    			  elements = $("img.lazyImage").slice(i - 10, i + 10);
    		  }
    		  elements.unveil();
    	  } else {
    		  $("img.lazyImage").unveil();
    	  }
      }
```

We added the following new function too:
```
    toggleUnveil : function() {
    	this.unveilImages = true;
    },
```

We edited the existing function _initList_ to add the class _lazyImage_ and attribute _data-src_ when rendering the images:
        ```
list.push(
          '<li>' +
            '<img' +
              ' class="lazyImage" ' +
              ' data-src="' + dataSrc + '"' +
              ' src="' + src + '"' +
              ' data-action="view"' +
              ' data-index="' +  i + '"' +
              ' data-original-url="' +  (url || src) + '"' +
              ' alt="' +  alt + '"' +
            '>' +
          '</li>'
        );
```
where dataSrc is obtained via a call:
`var dataSrc = this.getAttribute('data-actualurl') || src;
`

In our calling code, we have to a reference to the files _viewer.js_ and _jquery.unveil.js_. Then our javascript call is:
```
$j(function($) {
	var modalViewerOptions = {
		url: 'data-original',
		shown: function(e) {
			$(this).viewer('toggleUnveil');
		}
	};

	// show 'modal' image viewer
	$('#invokeImageViewer').on('click', function(e) {
		e.preventDefault();
		$('#hiddenThumbs').viewer(modalViewerOptions).viewer('show');
	});
});
```
An actual thumbnail image:
`<img src="commonImage.png" data-actualurl="actualThumbnailImage.png"  alt="Image description" data-original="actualFullSizeImage.png"/>`

Hope that helps you get started.
