### ISSUE TITLE
显示图片很慢

### ISSUE THREAD

**Issue by piglingcn** [fengyuanchen/viewer#3]
当点击图片时显示很慢，偶尔会快一点点~~
但是一旦设置transition:false时，那是一瞬间打开！性能希望能调一下~~

**Comment by piglingcn** [comment]
多个图片的时候，一开始比如点击第二个关掉，然后点开第一个，还是会显示之前的第二个。。
还有一个是有多个图片，然后页面上删除其中一个，再点开其中一张图，原来删除的还会余留在下方的相册中

**Comment by fengyuanchen** [comment]
1. The speed mostly depends on the net speed (transition only has 0.3s delay).
2. The error of multiple images viewimg had fixed at #2.
3. Update dynamically not support now, may be added later, you can restart the viewer manually after delete an image at present.

**Comment by fengyuanchen** [comment]
As of v0.4.0, I had added a new "update" method for update the images in the viewer dynamically.
