### ISSUE TITLE
想显示一个按钮，查看原图，链接与展示的不同

### ISSUE THREAD

**Issue by hujghc** [fengyuanchen/viewer#31]
RT

如何设置？

**Comment by fengyuanchen** [comment]
不要复杂化了，可以使用`url`参数配置缩略图和原图。

**Comment by hujghc** [comment]
好的。

**Comment by seed-fe** [comment]
可以自己制作一个查看原图的按钮（a标签），`shown`事件时显示，`hidden`事件时隐藏，`viewed`事件时执行一个函数，取得当前显示的缩略图的`data-original`属性中存储的原图的url，然后赋值给查看原图按钮的href属性，我自己试了一下，大致思路是这样的 @hujghc

**Comment by hujghc** [comment]
@seed-fe 多谢，我已经fork了一份，改了，大概思路也是这样的。
