### ISSUE TITLE
如果渲染一个列表里面的图片，怎么设置某些图片不能被查看，就不进入modal模式？

### ISSUE THREAD

**Issue by mobei** [fengyuanchen/viewer#37]

**Comment by caishun2013** [comment]
同问

**Comment by fengyuanchen** [comment]
暂不支持筛选过滤图片。稍微改下源码就可以满足你们自己需求了。

**Comment by jacksplwxy** [comment]
在源码种找到element.querySelectorAll进行设置，即可过滤掉不想要要的图片。有空的朋友提个pr吧，这个需求还是挺常用的 @mobei @caishun2013

**Comment by fengyuanchen** [comment]
请使用 [Viewer.js](https://github.com/fengyuanchen/viewerjs) 的 `filter` 参数函数过滤不需要查看的图片。
