### ISSUE TITLE
图片预览窗很容易被别的样式给污染

### ISSUE THREAD

**Issue by piglingcn** [fengyuanchen/viewer#4]
比如
< div class="xxx">
    < ul>
    < li>
      < img src="xx" />
    </ li>
  </ ul>
</ div>

.xxx ul{...}
.xxx ul li{...}

**Comment by fengyuanchen** [comment]
一个组件一旦放入某个页面中，那么它的样式肯定是很容易受影响的，这种情况无法避免。唯一的办法是进入避免污染组件的样式，以你的例子为例：

```css
.xxx > ul {...}
.xxx > ul > li {...}
```
