### ISSUE TITLE
chrome浏览器  ***点击旋转**** 滚轮放大或缩小 ****会有竖线

### ISSUE THREAD

**Issue by zhihuiWang3225** [fengyuanchen/viewer#47]
在chrome浏览器下，先点击旋转，再用滚轮去放大或者缩小（操作一定要快），会有图片的虚边一层层的显示在页面中，过几秒会消失。但是这个间接的效果不好，请问能不能处理

**Comment by fengyuanchen** [comment]
这是浏览器渲染问题吧。
