### ISSUE TITLE
加载的时候是否可以加个LOADING效果呢？

### ISSUE THREAD

**Issue by Fazime** [fengyuanchen/viewer#49]
这是一款非常棒的插件，最近在使用过程中，感觉大图片加载慢，加载的时候是否可以加个LOADING效果呢？

**Comment by fengyuanchen** [comment]
加载时，图片会从上到下一点点显示出来。

**Comment by Fazime** [comment]
![qq 20170910180646](https://user-images.githubusercontent.com/15311147/30248021-e5201888-9652-11e7-8199-51651eca7d9b.png)
在下不才，将阁下的viewerjs做了大改。效果如图

**Comment by Fazime** [comment]
主要用在移动端

**Comment by Fazime** [comment]
loading效果是加在 view method下吧？然后viewd结束？

**Comment by sushuier** [comment]
@Fazime 佩服之情，油然而生

**Comment by fengyuanchen** [comment]
[Viewer.js](https://github.com/fengyuanchen/viewerjs) 已支持 Loading 效果。

对于 jQuery 用户，请使用纯插件版： https://fengyuanchen.github.io/jquery-viewer/
