### ISSUE TITLE
关闭时的bug

### ISSUE THREAD

**Issue by hyguang** [fengyuanchen/viewer#55]
有没有谁遇到过, 在移动端, 用双指缩放放大之后, 点关闭按钮, 图片没了, 但是modal框还在? 怎么处理?

**Comment by oliviazhangjuan** [comment]
我也遇到了。。。

**Comment by hyguang** [comment]
@oliviazhangjuan 解决没?我这边是图片关了,modal框还在,点击navbar的图还可以继续显示图片,但是关闭按钮就没任何反应了
