### ISSUE TITLE
在一组图片中使用viewer,当动态改变图片数组以后，要怎样初始化viewer，让它显示新的一组图片？

### ISSUE THREAD

**Issue by alinai94** [fengyuanchen/viewer#58]
destroy（）应该如何调用？
/******
viewer = box.viewer({
      url: 'data-original',
});
$(‘.close').click(function(){
      viewer.destroy();
});
*******/
页面报错：
 Uncaught TypeError: viewer.destroy is not a function

**Comment by fengyuanchen** [comment]
注销重启？
