### ISSUE TITLE
Show the first image after the last one (cyclic scrolling)

### ISSUE THREAD

**Issue by gvitali** [fengyuanchen/viewer#59]
Hi!
How to enable a switching to the first image after the last one and to the last image if scroll to left for the first one (cyclic scrolling)?
Thank you!

**Comment by fengyuanchen** [comment]
Please use [Viewer.js](https://github.com/fengyuanchen/viewerjs) which support [custom toolbar](https://github.com/fengyuanchen/viewerjs/blob/master/examples/custom-toolbar.html).
