### ISSUE TITLE
标题不能正常显示(The title do not show properly)

### ISSUE THREAD

**Issue by TangJiaLin** [fengyuanchen/viewer#6]
首先，请原谅我可能很难读懂的英文。下面我将描述这个情况。
(First, Please ignore my bad English. Next, I will describe this question.)

使用版本：Viewer v0.4.0
(Version:Viewer v0.4.0)

在实例化插件并打开图片后，Viewer没有按照我想的显示标题。
(After the instantiation and open image, Viewer shows no title.)
在查看源码后我发现，在view函数中，标题的显示是通过绑定EVENT_VIEWED事件，并触发该事件后才显示。
(After see the source, At function view, After the title displayed in the bind EVENT_VIEWED, and trigger this event.)
但是在使用中，我发现EVENT_VIEWED事件会在绑定之前触发。所以导致标题无法正常显示。
(But, I see trigger EVENT_VIEWED at before bind EVENT_VIEWED. So title do not show.)
在我的代码中，我注释了EVENT_VIEWED事件，并在这个位置直接显示了标题，并期待有更好的做法。
(At my source, I hide event EVENT_VIEWED, And in this position at once show title,I look forward to have better way.)

最后,感谢这个插件给我的帮助.
(Thank you for yours plug-in's help for me.)

**Comment by fengyuanchen** [comment]
Maybe the `viewed` event is bound too late, I will move it forward

**Comment by TangJiaLin** [comment]
可以正常显示了,谢谢!
(It can show properly, Thanks!)
