### ISSUE TITLE
图片rorate效果

### ISSUE THREAD

**Issue by iygnol** [fengyuanchen/viewer#66]
有这么一种需求：
当用户浏览图片的时候，他发现图片是倒过来的或者是横着的，他可以转动图片，但是当他下次再次浏览这
个图片的时候，他还得重新转动图片。
当前处理方法：记录用户转动的角度，保存在服务器，然后当图片加载的时候自动转动到上一次的角度（这个过程有一个转动的动画）。这样做效果不是特别好，因为转动的动画效果是不必要的，我想有没有办法把这个转动效果去掉，也就是初始化的时候直接是转动后的角度（包括小图）？

**Comment by fengyuanchen** [comment]
- 方法1：直接禁用动画效果（`transition: false`）。
- 方法2：旋转之前，查找Viewer中所有包含`class="viewer-transition"`的元素，移除该类。
