### ISSUE TITLE
Can't support IE8 ?

### ISSUE THREAD

**Issue by jusonleo** [fengyuanchen/viewer#7]
When I visit http://fengyuanchen.github.io/viewer/ , I found the demo can't use rotate and flip function in IE8 .  What's wrong with me ?

**Comment by fengyuanchen** [comment]
The rotation and flip features require CSS3 2D Transforms support (IE 9+).

**Comment by jusonleo** [comment]
Thanks for your answer . Do you have plan to resolve it ?

**Comment by fengyuanchen** [comment]
Resolve it? Are you sure?

**Comment by fengyuanchen** [comment]
BTW, the only plan I can do is kill IE8 forever.

**Comment by pw8118** [comment]
IE8下1819行，Object.defineProperty函数报错，“不支持此操作”，请问有办法解决吗？

**Comment by fengyuanchen** [comment]
@pw8118 Only IE9+ supports [`Object.defineProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Browser_compatibility).
