### ISSUE TITLE
一个bug，在iframe里面用到了viewer结果不能全屏，图片拉长

### ISSUE THREAD

**Issue by ice-orange-xi** [fengyuanchen/viewer#79]
图片显示不好看，非得拉长。关闭图片得向上拉呀，贼费劲。
![QQ图片20190605214555](https://user-images.githubusercontent.com/46749635/58961288-6d215780-87db-11e9-94fc-98b26b6a3cd4.png)
![QQ图片20190605214602](https://user-images.githubusercontent.com/46749635/58961299-70b4de80-87db-11e9-9ed9-9925049997f6.png)
![QQ图片20190605214606](https://user-images.githubusercontent.com/46749635/58961308-74486580-87db-11e9-8a63-db62a1a5b91d.png)

**Comment by fengyuanchen** [comment]
不支持在 iframe 中使用。
