### ISSUE TITLE
图片可以支持传参数设置默认旋转角度吗

### ISSUE THREAD

**Issue by gaoruihappy** [fengyuanchen/viewer#81]
图片可以支持传参数设置默认旋转角度吗

**Comment by fengyuanchen** [comment]
你可以自定义工具栏上的旋转按钮， 调用 `rotate` 方法实现自定义旋转角度。

- `rotate` 方法文档：https://github.com/fengyuanchen/viewerjs#rotatedegree
- 自定义工具栏示例： https://fengyuanchen.github.io/viewerjs/examples/custom-toolbar.html
